### ISSUE TITLE
Question: is a different endpoint generated per deploy context?

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#13]
I'm not completely sure how this work on Nimbella's end, but is a separate endpoint created per deploy context?

e.g. if I run the plugin from a production context, then from a branch/Deploy Preview context would those endpoints co-exist on Nimbella's end?

**Comment by rabbah** [comment]
Not right now. As suggested, we'll restrict the deployment to production contexts only (not previews).

**Comment by satyarohith** [comment]
I'm considering this question answered and closing the issue. Please feel free to re-open.
