### ISSUE TITLE
Bug: plugin is not compatible with Windows

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#19]
The plugin uses `process.env.HOME` which is not available on Windows.
https://github.com/nimbella/netlify-plugin-nimbella/blob/2969462b33aa84d0c44a0c82285dc55e7a439f44/index.js#L77
As a result running `netlify build` will fail on Windows.

A possible fix can be to use `require('os').homedir()`

**Comment by rabbah** [comment]
Arguably we can drop this logic altogether and execute the login command every time. 
In either case, we should handle the failure to login or retrieve the active namespace.
Related to #23.

**Comment by satyarohith** [comment]
> Arguably we can drop this logic altogether and execute the login command every time.

I found it to be taking a bit of time for login so I'm caching the directory. 

> In either case, we should handle the failure to login or retrieve the active namespace.

If nim fails to login, the error reported by nim is returned by the plugin. It's handled in `try/catch`
