### ISSUE TITLE
Bug: outdated error message about missing token

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#22]
Related to https://github.com/nimbella/netlify-plugin-nimbella/issues/12
I might be wrong but https://github.com/nimbella/netlify-plugin-nimbella/blob/2969462b33aa84d0c44a0c82285dc55e7a439f44/index.js#L70 seems outdated as the current working flow is to add `NIMBELLA_LOGIN_TOKEN` as an env variable.

**Comment by rabbah** [comment]
An `addons:create` will generate a `NIMBELLA_LOGIN_TOKEN` and it is added to the environment for the build automatically. 

The `addons:auth` allows a developer to claim their account in the Nimbella portal and access the corresponding dashboard. It doesn't affect the build but is a convenience for developers to be able to use the Nimbella CLI and Workbench.

**Comment by erezrokah** [comment]
Oh cool, I thought the token is not valid until users run `addons:auth`
