### ISSUE TITLE
Refactor: use netlify-redirect-parser to parse netlify.toml redirects

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#34]
Instead of parsing `netlify.toml` as a `toml` file you could use `require('netlify-redirect-parser').parseNetlifyConfig`

**Comment by rabbah** [comment]
@erezrokah when using this function, do we pass the path to the `toml` file (like in these tests https://github.com/netlify/netlify-redirect-parser/blob/57afec6ba052f21b1146cb61e3c48591f85e8d53/netlify-config-parser.test.js#L9)?

**Comment by rabbah** [comment]
A related question @erezrokah  - is there a programmatic way of generating the `_redirects` file (the dual of a parser)? What is the best practice for generating desired redirects for a site (is writing new rules to the `_redirects` the best approach)?

**Comment by rabbah** [comment]
Closed by https://github.com/nimbella/netlify-plugin-nimbella/pull/57.
