### ISSUE TITLE
Performance: consider uploading files in parallel 

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#35]
Could this loop be done in parallel?
https://github.com/nimbella/netlify-plugin-nimbella/blob/beca8fd4b911f939de21ec47a018ba4dfbbe1afa/index.js#L31

Considering this uploads files it could improve performance.

**Comment by satyarohith** [comment]
I tried to achieve this but the output was a bit distorted. Would be a nice improvement for a future release. Thanks for your suggestion. :)

**Comment by ehmicky** [comment]
Removing the initial `Deploy ${file}...` might help make the logs less distorted:

```js
await Promise.all(files.map(async file => {
  const [actionName, extension] = file.split('.');
  let command =
    `nim action update ${actionName} ${join(functionsDir, file)} ` +
    `--timeout=${Number(timeout)} --memory=${Number(memory)} ` +
    `--web=raw `;

  if (extension === 'js') {
    command += '--kind nodejs-lambda:10 --main handler';
  }

  // Note: since stdout: 'ignore' is used, the returned `stdout` will always be empty
  const {stderr, exitCode} = await run.command(command, { reject: false, stdout: 'ignore' });
  const message = exitCode === 0 ? 'done.' : String(stderr)
  console.log(`Deployed ${file}: ${message}`)
}))
```

If the files must be sorted in the logs, it could also be possible to do a single `console.log()` after all files have been deployed.

**Comment by satyarohith** [comment]
Thanks for the suggestion, @ehmicky! :)
