### ISSUE TITLE
Bug(docs): the link to `Learn more about Nimbella's integration for Netlify from` in the readme results in 404

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#4]
As a part of reviewing https://github.com/netlify/plugins/pull/155 I noticed the link to learn more about the integration is broken.

**Comment by satyarohith** [comment]
Thanks for opening the issue, @erezrokah! The page was planned to be rolled out in a couple of days but I've removed it for now. I'll add it back once it's ready. And I updated the plugin PR as well. :)
